import Head from 'next/head';
import { useEffect, useState } from 'react';

import { Results } from '@/components/Results';
import { Search } from '@/components/Search';
import type { Person } from '@/types/result';

const Home = () => {
    const [results, setResults] = useState<Person[] | null>(null);
    const [isFetching, setIsFetching] = useState(false);
    const [error, setError] = useState<string | null>(null);

    useEffect(() => {
        if (isFetching) {
            const fetchData = async () => {
                setResults(null);
                setError(null);
                try {
                    const response = await fetch(
                        'https://gc-interview-api.azurewebsites.net/api/consultants',
                    );

                    if (!response.ok) {
                        throw new Error('HTTP error ' + response.status);
                    }

                    const data = (await response.json()) as Person[];

                    setResults(data);
                } catch (error) {
                    setError('Sorry, something went wrong. Please try again.');
                }
            };

            void fetchData();
        }
    }, [isFetching]);

    useEffect(() => {
        if (results !== null || error !== null) {
            setIsFetching(false);
        }
    }, [results, error]);

    useEffect(() => {
        setTimeout(() => setIsFetching(true), 500);
    }, []);

    return (
        <>
            <Head>
                <title>Create T3 App</title>
                <meta
                    name="description"
                    content="Generated by create-t3-app"
                />
                <link
                    rel="icon"
                    href="/favicon.ico"
                />
            </Head>
            <main className="flex min-h-screen flex-col items-center justify-center bg-white">
                <Search />
                <Results
                    errorMessage={error !== null ? error : undefined}
                    loading={isFetching}
                    results={results}
                />
            </main>
        </>
    );
};

export default Home;
