import Head from 'next/head';
import Link from 'next/link';

import { Results } from '@/components/Results';

export default function Home() {
    return (
        <>
            <Head>
                <title>Create T3 App</title>
                <meta
                    name="description"
                    content="Generated by create-t3-app"
                />
                <link
                    rel="icon"
                    href="/favicon.ico"
                />
            </Head>
            <main className="flex min-h-screen flex-col items-center justify-center bg-white">
                <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
                    <Results />
                </div>
            </main>
        </>
    );
}
